In [1]:
using LinearAlgebra, Distributions, Statistics, SparseArrays

In [2]:
include("../src/cmvn.jl")
include("../src/generate.jl")
include("../src/mvn.jl")

expt_tnorm

In [3]:
iters = 10
ms = [16, 32]; ds = [1, 2, 4, 8, 16]
ans_1 = zeros(length(ms), length(ds)); time_1 = zeros(length(ms), length(ds))
# ans_2 = zeros(length(ms), length(ds)); time_2 = zeros(length(ms), length(ds))

for i in 1:length(ms)
    for j in 1:length(ds)
        m = ms[i]; d = ds[j]
        for p in 1:iters
            Σ = Σ_generate(m)
            a = fill(-Inf, m)
            b = rand(Uniform(0, m), m)
            if d ≤ 4
                time_1[i, j] += @elapsed (ans_1[i, j] += CMVN(Σ, a, b, d, ns = 5, N = 200)[1])
#             time_2[i, j] += @elapsed ans_2[i, j] += RCMVN(Σ, a, b, d, m)[1]
            elseif d ≤ 8
                time_1[i, j] += @elapsed (ans_1[i, j] += CMVN(Σ, a, b, d, ns = 10, N = 400)[1])
#             time_2[i, j] += @elapsed ans_2[i, j] += RCMVN(Σ, a, b, d, m)[1]
            else
                time_1[i, j] += @elapsed (ans_1[i, j] += CMVN(Σ, a, b, d, ns = 10, N = 1000)[1])
#             time_2[i, j] += @elapsed ans_2[i, j] += RCMVN(Σ, a, b, d, m)[1]
            end
        end
    end
end
ans_1 ./= iters; time_1 ./= iters
# ans_2 ./= iters; time_2 ./= iters

2×5 Array{Float64,2}:
 0.00137262   0.00798679  0.0109655  0.094489  0.532558
 0.000146171  0.00757186  0.0204123  0.234775  1.12486 

In [4]:
# todo: fix NaN issue
ans_1

2×5 Array{Float64,2}:
 0.639989  0.840737  NaN  NaN    0.824595
 0.610716  0.781834  NaN  NaN  NaN       

In [5]:
time_1

2×5 Array{Float64,2}:
 0.00137262   0.00798679  0.0109655  0.094489  0.532558
 0.000146171  0.00757186  0.0204123  0.234775  1.12486 