In [1]:
using LinearAlgebra, Distributions, Statistics

In [22]:
include("../src/cao2019.jl")

RCMVN (generic function with 1 method)

In [58]:
m = 8; d = 2
Σ = Σ_generate(m)
a = fill(-Inf, m)
b = rand(Uniform(0, m), m)
CMVN(Σ, a, b, d, m)

(0.5824284428107045, [2.1022066375021207e-14, 2.1022066375021207e-14, 3.020133145511626e-16, 3.020133145511626e-16, 0.0, 0.0, 8.573248217379685e-7, 8.573248217379685e-7])

In [59]:
    s = Int(m / d)
    y = zeros(m)
    P = 1.
    L, D = LDL(copy(Σ), m, d)

([1.0 0.0 … 0.0 0.0; 0.0 1.0 … 0.0 0.0; … ; 0.022176353772189083 0.36028379648534525 … 1.0 0.0; -0.1422318904917367 0.012758366378214779 … 0.0 1.0], [0.32638105209619106 0.07014344502339027 … 0.0 0.0; 0.07014344502339027 0.45992808560215825 … 0.0 0.0; … ; 0.0 0.0 … 0.3553355156189327 -0.1288192593601408; 0.0 0.0 … -0.1288192593601408 0.7239223204996089])

In [60]:
D

8×8 Array{Float64,2}:
 0.326381   0.0701434   0.0           0.0         …   0.0         0.0        
 0.0701434  0.459928    0.0           0.0             0.0         0.0        
 0.0        0.0         0.65603      -0.0554238       0.111683   -0.000988594
 0.0        0.0        -0.0554238     0.674219       -0.147487   -0.166005   
 0.0        0.0         0.0529583    -0.0124057      -0.0344284  -0.106467   
 0.0        0.0         0.0262063     0.00116478  …   0.059026    0.0120978  
 0.0        0.0         0.111683     -0.147487        0.355336   -0.128819   
 0.0        0.0        -0.000988594  -0.166005       -0.128819    0.723922   

In [29]:
iters = 250
ms = [16, 32]; ds = [1, 2, 4, 8, 16]
ans_1 = zeros(length(ms), length(ds)); time_1 = zeros(length(ms), length(ds))
ans_2 = zeros(length(ms), length(ds)); time_2 = zeros(length(ms), length(ds))

for i in 1:length(ms)
    for j in 1:length(ds)
        m = ms[i]; d = ds[j]
        println(m, d)
        for p in 1:iters
            Σ = Σ_generate(m)
            a = fill(-Inf, m)
            b = rand(Uniform(0, m), m)
            time_1[i, j] += @elapsed ans_1[i, j] += CMVN(Σ, a, b, d, m)[1]
            time_2[i, j] += @elapsed ans_2[i, j] += RCMVN(Σ, a, b, d, m)[1]
        end
    end
end
ans_1 ./= iters; time_1 ./= iters
ans_2 ./= iters; time_2 ./= iters

161
162


PosDefException: PosDefException: matrix is not Hermitian; Cholesky factorization failed.

In [9]:
ans_1

4×5 Array{Float64,2}:
 0.796505  0.790106  0.744898  0.757142  0.763244
 0.79294   0.795603  0.799778  0.748595  0.771389
 0.795454  0.797203  0.761744  0.781774  0.774206
 0.771363  0.774111  0.779079  0.772615  0.787353

In [10]:
time_1

4×5 Array{Float64,2}:
 0.878787  0.870232  0.768169  0.835823  0.931738
 1.69668   1.72158   1.53412   1.51159   1.65992 
 3.5116    3.45296   3.10521   3.04589   3.29766 
 6.79749   6.96986   6.12449   5.99862   6.59756 

In [11]:
ans_2

4×5 Array{Float64,2}:
 0.795339  0.788527  0.74479   0.756972  0.762919
 0.794195  0.795849  0.799149  0.748423  0.772367
 0.794212  0.797515  0.762233  0.781643  0.773981
 0.770848  0.775071  0.779909  0.772041  0.787305

In [12]:
time_2

4×5 Array{Float64,2}:
 0.874459  0.87119  0.772278  0.825405  0.890534
 1.70076   1.72084  1.53631   1.51634   1.66227 
 3.43803   3.46523  3.11108   3.03534   3.30214 
 6.92552   7.01506  6.15967   6.0102    6.63187 