In [1]:
versioninfo()

Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)


In [2]:
using LinearAlgebra, Distributions, Statistics

In [3]:
include("../src/cmvn.jl")
include("../src/generate.jl")
include("../src/mvn.jl")

expt_tnorm

In [4]:
iters = 10
ms = [16, 32, 64, 128]; ds = [1, 2, 4, 8, 16]
ans_1 = zeros(length(ms), length(ds)); time_1 = zeros(length(ms), length(ds))
# ans_2 = zeros(length(ms), length(ds)); time_2 = zeros(length(ms), length(ds))

for i in 1:length(ms)
    for j in 1:length(ds)
        m = ms[i]; d = ds[j]
        for p in 1:iters
            Σ = Σ_generate(m)
            a = fill(-Inf, m)
            b = rand(Uniform(0, m), m)
            if d ≤ 4
                time_1[i, j] += @elapsed (ans_1[i, j] += CMVN(Σ, a, b, d, ns = 5, N = 200)[1])
#             time_2[i, j] += @elapsed ans_2[i, j] += RCMVN(Σ, a, b, d, m)[1]
            elseif d ≤ 8
                time_1[i, j] += @elapsed (ans_1[i, j] += CMVN(Σ, a, b, d, ns = 10, N = 400)[1])
#             time_2[i, j] += @elapsed ans_2[i, j] += RCMVN(Σ, a, b, d, m)[1]
            else
                time_1[i, j] += @elapsed (ans_1[i, j] += CMVN(Σ, a, b, d, ns = 10, N = 1000)[1])
#             time_2[i, j] += @elapsed ans_2[i, j] += RCMVN(Σ, a, b, d, m)[1]
            end
        end
    end
end
ans_1 ./= iters; time_1 ./= iters
# ans_2 ./= iters; time_2 ./= iters

4×5 Array{Float64,2}:
 0.00184168   0.0127112  0.0201883  0.166684  0.807052
 0.000260183  0.0137821  0.036998   0.298703  1.47424 
 0.00096081   0.0255036  0.078845   0.590469  2.8738  
 0.00610764   0.0537313  0.150856   1.22054   5.65662 

In [5]:
ans_1

4×5 Array{Float64,2}:
 0.756518  0.740422  0.81904   0.636046  0.707965
 0.614726  0.861409  0.730301  0.84626   0.858747
 0.547702  0.747538  0.895432  0.840643  0.829653
 0.62667   0.724664  0.822285  0.684904  0.774255

In [6]:
time_1

4×5 Array{Float64,2}:
 0.00184168   0.0127112  0.0201883  0.166684  0.807052
 0.000260183  0.0137821  0.036998   0.298703  1.47424 
 0.00096081   0.0255036  0.078845   0.590469  2.8738  
 0.00610764   0.0537313  0.150856   1.22054   5.65662 

In [7]:
using Random 
Random.seed!(10);

In [8]:
m = 32; d = 16
Σ = Σ_generate(m)
a = fill(-Inf, m)
b =zeros(m)
p, y = CMVN(Σ, a, b, d, ns = 10, N = 1000)

(1.0931084233935071e-10, [-0.6446152472711251, -0.3798457189788842, -0.21720184057384997, -0.5164189877923169, -0.5653422149252472, -0.5455304135274137, -0.058036450055581945, -0.34626328606483375, -0.5031971378531659, -0.31095258534960535  …  -0.7905605706373686, -1.5850776970029121, -0.0015850809069268702, 0.3896444883589674, -0.39503636296724304, -0.5373602909095967, -0.5677814780726252, -0.051432954649116236, 0.24311024156206695, 0.20575685281041345])

In [9]:
p # should be zero

1.0931084233935071e-10