In [1]:
using LinearAlgebra, Distributions, Statistics

In [1]:
include("../src/cao2019.jl")

RCMVN (generic function with 1 method)

## todo: 

* implement algorithm 4 in Cao2019
* load `choldecomp_hmatrix` from http://www.h2lib.org/
* write `row_offset()` and `col_offset()`
* define `hcmvn_comv_func` such as `hcmvn_MC`, `hcmvn_CMVN` or with case/switch statement
* move function to src folder
* reproduce table 4 and 5

In [1]:
using HierarchicalMatrices

┌ Info: Precompiling HierarchicalMatrices [7c893195-952b-5c83-bb6e-be12f22eed51]
└ @ Base loading.jl:1242


In [14]:
Σ = [1.0 0.5; 0.5 1]

2×2 Array{Float64,2}:
 1.0  0.5
 0.5  1.0

In [117]:
@hierarchical MyHierarchicalMatrix LowRankMatrix [1.0 2; 3 4]

ErrorException: syntax: invalid syntax 1 2

In [61]:
T = Float64

Float64

In [112]:
A = MyHierarchicalMatrix(2, 3)

0×0 MyHierarchicalMatrix{Float64}

In [115]:
A.assigned

2×3 Array{Int64,2}:
 0  0  0
 0  0  0

In [116]:
A.assigned = [1 2 3; 4 5 6]

ErrorException: setfield! immutable struct of type MyHierarchicalMatrix cannot be changed

In [106]:
[1.0 2; 3 4]

2×2 Array{Float64,2}:
 1.0  2.0
 3.0  4.0

In [89]:
A.Matrixblocks = [1.0 2; 3 4]

MethodError: MethodError: Cannot `convert` an object of type Float64 to an object of type Array{Float64,2}
Closest candidates are:
  convert(::Type{T<:Array}, !Matched::AbstractArray) where T<:Array at array.jl:474
  convert(::Type{T<:AbstractArray}, !Matched::T<:AbstractArray) where T<:AbstractArray at abstractarray.jl:14
  convert(::Type{T<:AbstractArray}, !Matched::Factorization) where T<:AbstractArray at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/LinearAlgebra/src/factorization.jl:46
  ...

In [69]:
A = [1 2.0 3; 4 5 6]
x = [1.0, 2, 3, 4]

4-element Array{Float64,1}:
 1.0
 2.0
 3.0
 4.0

In [70]:
A

2×3 Array{Float64,2}:
 1.0  2.0  3.0
 4.0  5.0  6.0

In [71]:
y = zero(x)
HierarchicalMatrices.mul!(y, A, x, 1, 1)

4-element Array{Float64,1}:
 14.0
 32.0
  0.0
  0.0

In [75]:
HierarchicalMatrices.mul!(y, A, x, 1, 1)

4-element Array{Float64,1}:
 28.0
 64.0
  0.0
  0.0

In [39]:
Σ.assigned([1.0 2 3; 4 5 6; 7 8 9])

MethodError: MethodError: objects of type Array{Int64,2} are not callable
Use square brackets [] for indexing an Array.

In [40]:
?assgined

search:

Couldn't find assgined
Perhaps you meant asind, signed or isassigned


No documentation found.

Binding `assgined` does not exist.


In [37]:
Σ.LowRankMatrixblocks

4×4 Array{LowRankMatrix{Float64},2}:
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef

MethodError: MethodError: no method matching cholesky(::MyHierarchicalMatrix{Float64})
Closest candidates are:
  cholesky(!Matched::Union{LinearAlgebra.Hermitian{Complex{T<:Real},SparseArrays.SparseMatrixCSC{Complex{T<:Real},Int64}}, LinearAlgebra.Hermitian{T<:Real,SparseArrays.SparseMatrixCSC{T<:Real,Int64}}, LinearAlgebra.Symmetric{T<:Real,SparseArrays.SparseMatrixCSC{T<:Real,Int64}}, SparseArrays.SparseMatrixCSC{T<:Real,Ti} where Ti<:Integer, SparseArrays.SparseMatrixCSC{Complex{T<:Real},Ti} where Ti<:Integer}; kws...) where T<:Real at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/SuiteSparse/src/cholmod.jl:1434
  cholesky(!Matched::Union{Union{DenseArray{T,2}, Base.ReinterpretArray{T,2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, Base.ReshapedArray{T,2,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, SubArray{T,2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, Base.AbstractCartesianIndex},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, Base.ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}} where T, Union{LinearAlgebra.Hermitian{#s612,#s611}, LinearAlgebra.Hermitian{Complex{#s612},#s611}, LinearAlgebra.Symmetric{#s612,#s611}} where #s611<:(Union{DenseArray{T,2}, Base.ReinterpretArray{T,2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, Base.ReshapedArray{T,2,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, SubArray{T,2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, Base.AbstractCartesianIndex},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, Base.ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}} where T) where #s612<:Real}) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/LinearAlgebra/src/cholesky.jl:275
  cholesky(!Matched::Union{Union{DenseArray{T,2}, Base.ReinterpretArray{T,2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, Base.ReshapedArray{T,2,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, SubArray{T,2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, Base.AbstractCartesianIndex},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, Base.ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}} where T, Union{LinearAlgebra.Hermitian{#s610,#s609}, LinearAlgebra.Hermitian{Complex{#s610},#s609}, LinearAlgebra.Symmetric{#s610,#s609}} where #s609<:(Union{DenseArray{T,2}, Base.ReinterpretArray{T,2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, Base.ReshapedArray{T,2,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, SubArray{T,2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, Base.AbstractCartesianIndex},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, Base.ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}} where T) where #s610<:Real}, !Matched::Val{false}; check) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/LinearAlgebra/src/cholesky.jl:275
  ...

In [22]:
Σ[1,1]

BoundsError: BoundsError: attempt to access 2×2 Array{Int64,2} at index [3, 3]

In [25]:
Σ.Matrixblocks

2×2 Array{Array{Float64,2},2}:
 #undef  #undef
 #undef  #undef

In [15]:
HierarchicalMatrixFactorization(Σ)

MethodError: MethodError: no method matching HierarchicalMatrixFactorization(::Array{Float64,2})
Closest candidates are:
  HierarchicalMatrixFactorization(!Matched::HierarchicalMatrix{T}, !Matched::Array{Array{T,2},2}) where T at /Users/kwlee/.julia/packages/HierarchicalMatrices/ylb3r/src/hierarchical.jl:72

In [16]:
Σ

2×2 Array{Float64,2}:
 1.0  0.5
 0.5  1.0

In [ ]:
function hcmvn(a::Array{Float64, 1}, b::Array{Float64, 1}, Σ::Symetric{Float64, Array{Float64, 2}}, 
        d::Int64, n::Int64; cmvn_func = CMVN)
    """
        Algorithm 4 in Cao2019
        Hierarchical-block conditioning algorithm
    """
    Σ = Matrix(Σ)
    x = zeros(n)
    P = 1.0
#     B, UV = choldecomp_hmatrix(Σ)
#     r = length(B)
#     m = n ÷ r
#     for i in 1:r
#         j = (i-1) * m
#         if i > 1
#             or = row_offset(UV[i-1])
#             oc = col_offset(UV[i-1])
#             l = dim(UV)
#             g = UV[i-1] * x[oc+1:oc+l]
#             a[or+1:or+l] -= g
#             b[or+1:or+l] -= g
#         end
#         a_i = a[j+1:j+m]; b_i = b[j+1:j+m]
#         P *= cmvn_func(a_i, b_i, 0, B[i] * transpose(B[i]))
#         x[j+1:j+m] = solve(B[i], exp_Xi)
#     end
    return P
end