In [1]:
versioninfo()

Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)


In [2]:
using LinearAlgebra
using Distributions

cd("../src")

include("hchol.jl")
include("mvn.jl")
include("truncnorm.jl")
include("hcmvn.jl")
include("cmvn.jl")

CMVN

## Test for mvns

In [3]:
dim = 16
m = 4
d = 2
a1 = repeat([-10.0], dim)
b1 = repeat([0.0], dim)
ns = 10

10

### 1. $\Sigma = I$

In [4]:
A = convert(Matrix{Float64}, LinearAlgebra.I(dim))
Σ = A*A'
L = cholesky(Σ).L
N = 1000
tol = 1e-8

1.0e-8

#### probabilities

In [5]:
mvn(L, a1, b1, ns = ns, N = N, tol = tol, μ = ones(Float64, length(a1)))

1.6116522399570697e-13

In [6]:
p, _ = CMVN(Symmetric(Σ), a1 - ones(Float64, length(a1)), b1 - ones(Float64, length(a1)), d; ns = ns, N = N, tol = tol)
p

1.611652239957063e-13

In [7]:
HMVN(a1, b1, Symmetric(Σ), m, ns = ns, N = N, tol = tol, μ = ones(Float64, length(a1)))

1.6116522399570704e-13

In [8]:
HCMVN(a1, b1, Symmetric(Σ), d, m, μ = ones(Float64, length(a1)))

1.6116522399570649e-13

In [9]:
mvn(L, a1, b1; ns = ns, N = N, tol = tol, μ = b1)

1.5258789062500003e-5

In [10]:
p, _ = CMVN(Symmetric(Σ), a1 - b1, b1 - b1, d; ns = ns, N = N, tol = tol)
p

1.52587890625e-5

In [11]:
HMVN(a1, b1, Symmetric(Σ), m; ns = ns, N = N, tol = tol, μ = b1)

1.5258789062500007e-5

In [12]:
HCMVN(a1, b1, Symmetric(Σ), d, m, μ = b1)

1.5258789062500007e-5

#### expectation

In [13]:
expt_tnorm(a1, b1, L)

16-element Array{Float64,1}:
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654

In [14]:
_, y = CMVN(Symmetric(Σ), a1, b1, d)
y

16-element Array{Float64,1}:
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654
 -0.7978845608028654

### 2. $\Sigma = AA'$

$A_{i,j} \sim N(0,1)$

In [15]:
A = rand(Normal(0,1), dim, dim)
Σ = A*A'
L = cholesky(Σ).L
N = 1000
tol = 1e-8

1.0e-8

#### probabilities

In [16]:
mvn(L, a1, b1, ns = ns, N = N, tol = tol, μ = ones(Float64, length(a1)))

2.2039154290415795e-101

In [17]:
p, _ = CMVN(Symmetric(Σ), a1 - ones(Float64, length(a1)), b1 - ones(Float64, length(a1)), d; ns = ns, N = N, tol = tol)
p

7.675224760397064e-15

In [18]:
HMVN(a1, b1, Symmetric(Σ), m, ns = ns, N = N, tol = tol, μ = ones(Float64, length(a1)))

2.401582368915958e-7

In [19]:
HCMVN(a1, b1, Symmetric(Σ), d, m, μ = ones(Float64, length(a1)))

3.459479570624498e-9

In [20]:
mvn(L, a1, b1; ns = ns, N = N, tol = tol, μ = b1 .- 2)

0.017973661121710695

In [21]:
p, _ = CMVN(Symmetric(Σ), a1 - (b1 .- 2), b1 - (b1 .- 2), d; ns = ns, N = N, tol = tol)
p

0.011633216997010545

In [22]:
HMVN(a1, b1, Symmetric(Σ), m; ns = ns, N = N, tol = tol, μ = b1 .- 2)

0.002552721795828241

In [23]:
HCMVN(a1, b1, Symmetric(Σ), d, m, μ = b1 .- 2)

0.0013979307415243314

#### expectation

In [24]:
expt_tnorm(a1, b1, L)

16-element Array{Float64,1}:
 -4.108163526715283  
 -5.27998105774036   
 -1.6752889017372647 
 -2.0279822964781005 
 -1.9297642793941487 
 -0.09839283306280047
 -4.7386189560922585 
 -2.292317322396495  
  1.4641286247027572 
 -2.0296111568878774 
 -6.559218500505544  
 -0.7290112320014376 
 -3.933776748752801  
 -3.0849199801166907 
 -2.8856180879654496 
 -3.291514960000635  

In [25]:
_, y = CMVN(Symmetric(Σ), a1, b1, dim)
y

16-element Array{Float64,1}:
 -4.108163526715283  
 -5.27998105774036   
 -1.6752889017372647 
 -2.0279822964781005 
 -1.9297642793941487 
 -0.09839283306280047
 -4.7386189560922585 
 -2.292317322396495  
  1.4641286247027572 
 -2.0296111568878774 
 -6.559218500505544  
 -0.7290112320014376 
 -3.933776748752801  
 -3.0849199801166907 
 -2.8856180879654496 
 -3.291514960000635  

In [26]:
_, y = CMVN(Symmetric(Σ), a1, b1, d)
y

16-element Array{Float64,1}:
 -3.4617872672571095 
 -3.146849053448183  
 -2.3646885707617997 
 -2.083917707366243  
 -5.048171181632641  
 -6.821336109257225  
 -1.331009118359096  
 -5.678610372419837  
 -3.868875006792197  
  0.8727267834103911 
 -2.0274820272448153 
 -1.6199209244213852 
 -0.1710485119935156 
 -1.21588031518748   
 -0.24970812012560795
 -0.080921614905504  